### Listar todas as tarefas
GET http://localhost:5273/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5273/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js",
    "descricao": "Estudar Node.js para desenvolver aplicações web",
    "categoriaId": "6d091456-5a2f-4b5a-98fc-f1a3b50a627d"
}


PUT: http://localhost:5273/tarefas/alterar/{id}
Content-Type: application/json
{
    "titulo": "Estudar c#",
    "descricao": "Estudar c# para desenvolver aplicações web",
    "categoriaId": "6d091456-5a2f-4b5a-98fc-f1a3b50a627d"
}

GET: http://localhost:5273/tarefas/naoconcluidas

GET: http://localhost:5273/tarefas/concluidas